
services:
  my-spring-boot-app:
    build: ./
    ports:
      - 9090:9090
    depends_on:
      - mysql-service
    restart: always
  mysql-service:
    image: mysql:8.0
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cgi_db
    restart: always
